import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Telephonedirectory.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class Telephonedirectory extends javax.swing.JFrame {

	/** Creates new form Telephonedirectory */
	public Telephonedirectory() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel2 = new javax.swing.JPanel();
		jButton3 = new javax.swing.JButton();
		jLabel15 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jInternalFrame1 = new javax.swing.JInternalFrame();
		jPanel3 = new javax.swing.JPanel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jComboBox1 = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();
		jTextField10 = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jLabel13 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jLabel14 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel16 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel2.setBackground(new java.awt.Color(0, 153, 153));

		jButton3.setText("Admin");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 20));
		jLabel15.setText("TELEPHONE DIRECTORY");

		jButton4.setText("User");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jButton4)
										.addGap(99, 99, 99)
										.addComponent(jLabel15)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												127, Short.MAX_VALUE)
										.addComponent(jButton3).addGap(24, 24,
												24)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				jPanel2Layout.createSequentialGroup().addContainerGap(21,
						Short.MAX_VALUE).addGroup(
						jPanel2Layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton4).addComponent(jButton3)
								.addComponent(jLabel15)).addContainerGap()));

		getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

		jInternalFrame1.setVisible(true);
		jInternalFrame1.getContentPane().setLayout(new java.awt.CardLayout());

		jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18));
		jLabel11.setText("Telephone Directory");

		jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18));
		jLabel12.setText("Search By :");

		jRadioButton1.setText("Telephone No");
		jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton1ActionPerformed(evt);
			}
		});

		jRadioButton2.setText("Name");
		jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton2ActionPerformed(evt);
			}
		});

		jRadioButton3.setText("Address");
		jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton3ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"First Name", "Middle Name", "Last Name" }));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"House no", "Area", "City", "District", "State" }));
		jComboBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox2ActionPerformed(evt);
			}
		});

		jTextField10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField10ActionPerformed(evt);
			}
		});

		jButton2.setText("Search");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18));
		jLabel13.setText("Enter :-");

		jTextArea1.setColumns(20);
		jTextArea1.setEditable(false);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14));
		jLabel14.setText("RESULT :-");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				176,
																				176,
																				176)
																		.addComponent(
																				jLabel11))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				44,
																				44,
																				44)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel13)
																														.addComponent(
																																jLabel14))
																										.addGap(
																												33,
																												33,
																												33)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jTextField10,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																297,
																																Short.MAX_VALUE)
																														.addComponent(
																																jRadioButton1)
																														.addGroup(
																																jPanel3Layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				jPanel3Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jRadioButton2)
																																						.addComponent(
																																								jRadioButton3))
																																		.addGap(
																																				79,
																																				79,
																																				79)
																																		.addGroup(
																																				jPanel3Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jComboBox2,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								97,
																																								javax.swing.GroupLayout.PREFERRED_SIZE)
																																						.addComponent(
																																								jComboBox1,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								javax.swing.GroupLayout.PREFERRED_SIZE)))
																														.addComponent(
																																jScrollPane1,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																297,
																																Short.MAX_VALUE)))
																						.addComponent(
																								jLabel12))))
										.addContainerGap(
												178,
												javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(
								jPanel3Layout.createSequentialGroup().addGap(
										214, 214, 214).addComponent(jButton2)
										.addGap(57, 57, 57).addComponent(
												jLabel17).addContainerGap(277,
												Short.MAX_VALUE)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(26, 26, 26)
										.addComponent(jLabel11)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel12,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18)
										.addComponent(jRadioButton1)
										.addGap(9, 9, 9)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jRadioButton2)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jRadioButton3)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(49, 49, 49)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel13)
														.addComponent(
																jTextField10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																34,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				46,
																				46,
																				46)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton2)
																						.addComponent(
																								jLabel17))
																		.addGap(
																				32,
																				32,
																				32)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				173,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				91,
																				91,
																				91)
																		.addComponent(
																				jLabel14)))
										.addContainerGap()));

		jInternalFrame1.getContentPane().add(jPanel3, "card3");

		jLabel1.setText("First Name :-");

		jLabel2.setText("Middle Name :-");

		jLabel3.setText("Last  Name :-");

		jLabel4.setText("Mobile No :-");

		jLabel5.setText("Address Details :");

		jLabel6.setText("House No :-");

		jLabel7.setText("Area :-");

		jLabel8.setText(" City  :-");

		jLabel9.setText("District :-");

		jLabel10.setText("State :-");

		jButton1.setText("SAVE");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel16.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				28,
																				28,
																				28)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jLabel16,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel1)
																														.addComponent(
																																jLabel2)
																														.addComponent(
																																jLabel3)
																														.addComponent(
																																jLabel4)
																														.addComponent(
																																jLabel6)
																														.addComponent(
																																jLabel7)
																														.addComponent(
																																jLabel8)
																														.addComponent(
																																jLabel9)
																														.addComponent(
																																jLabel10)
																														.addComponent(
																																jLabel5))
																										.addGap(
																												50,
																												50,
																												50)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																jTextField5,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																216,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField4)
																														.addComponent(
																																jTextField3)
																														.addComponent(
																																jTextField2)
																														.addComponent(
																																jTextField1)
																														.addComponent(
																																jTextField6)
																														.addComponent(
																																jTextField7)
																														.addComponent(
																																jTextField8)
																														.addComponent(
																																jTextField9)))))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				225,
																				225,
																				225)
																		.addComponent(
																				jButton1)))
										.addContainerGap(235, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(53, 53, 53)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel1)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(27, 27, 27)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel3)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(23, 23, 23)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(28, 28, 28)
										.addComponent(jLabel5)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel7)
																		.addGap(
																				34,
																				34,
																				34)
																		.addComponent(
																				jLabel8))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jTextField7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																29,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel10)
														.addComponent(
																jTextField9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(29, 29, 29)
										.addComponent(jButton1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel16)
										.addContainerGap(67, Short.MAX_VALUE)));

		jInternalFrame1.getContentPane().add(jPanel1, "card2");

		getContentPane().add(jInternalFrame1, java.awt.BorderLayout.PAGE_END);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			jPanel1.setVisible(false);
			jInternalFrame1.remove(jPanel1);
			jInternalFrame1.repaint();
			jInternalFrame1.revalidate();
			jInternalFrame1.add(jPanel3);

		} catch (Exception e) {
		}

	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		String pass = "hello";
		String option = JOptionPane
				.showInputDialog(null, "Enter your Password");
		if (option.equals(pass)) {
			try {
				jPanel3.setVisible(false);
				jInternalFrame1.remove(jPanel3);
				jInternalFrame1.repaint();
				jInternalFrame1.revalidate();
				jInternalFrame1.add(jPanel1);

			} catch (Exception e) {
			}
		} else {
			JOptionPane.showMessageDialog(null,
					"oops..!! Please enter correct password.");
		}

	}

	String fname, lname, mname, houseno, area, city, district, state,
			mobileno_string;
	long mobileno_long;

	private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			String value, query = null;
			ResultSet resultSet = null;
			DatabaseAdapter adapter = new DatabaseAdapter();
			if (jRadioButton1.isSelected()) {
				value = jTextField10.getText();
				mobileno_long = Long.parseLong(value);
				query = "select * from telephonedir where mnumber = "
						+ mobileno_long;
				resultSet = adapter.getTableData(query);
			} else if (jRadioButton2.isSelected()) {

				int i = jComboBox1.getSelectedIndex();
				value = jTextField10.getText();

				switch (i) {
				case 0:
					query = "select * from telephonedir where FNAME='" + value
							+ "'";
					break;
				case 1:
					query = "select * from telephonedir where mname = '"
							+ value + "'";
					break;
				case 2:
					query = "select * from telephonedir where lname ='" + value
							+ "'";
					break;
				default:
					break;
				}

				resultSet = adapter.getTableData(query);

			} else if (jRadioButton3.isSelected()) {
				int i = jComboBox2.getSelectedIndex();
				value = jTextField10.getText();
				switch (i) {
				case 0:
					query = "select * from telephonedir where hnum = '" + value
							+ "'";
					break;
				case 1:
					query = "select * from telephonedir where area = '" + value
							+ "'";
					break;
				case 2:
					query = "select * from telephonedir where city = '" + value
							+ "'";
					break;
				case 3:
					query = "select * from telephonedir where district = '"
							+ value + "'";
					break;
				case 4:
					query = "select * from telephonedir where state= '" + value
							+ "'";
					break;
				default:
					break;
				}

				resultSet = adapter.getTableData(query);
			}

			while (resultSet.next()) {
				fname = resultSet.getString(1);
				mname = resultSet.getString(2);
				lname = resultSet.getString(3);
				mobileno_string = String.valueOf(resultSet.getLong(4));
				houseno = resultSet.getString(3);
				area = resultSet.getString(6);
				city = resultSet.getString(7);
				district = resultSet.getString(8);
				state = resultSet.getString(9);
				jLabel17.setText("selected info is fetched ..!!");
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			jLabel17.setText("Plz select your choice properly..!!");
		}
		jTextArea1.setText("First Name  :- " + fname + "\nMiddle Name :-"
				+ mname + "\nLast Name  :-" + lname + "\nMobile " + "Number :-"
				+ mobileno_string + "\nAddress :\n        Area:-" + area
				+ "\n        City :-" + city + "\n        District :-"
				+ district + "\n        State :-" + state);

	}

	private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			fname = jTextField1.getText();
			lname = jTextField2.getText();
			mname = jTextField3.getText();
			mobileno_long = Long.parseLong(jTextField4.getText());
			houseno = jTextField5.getText();
			area = jTextField6.getText();
			city = jTextField7.getText();
			district = jTextField8.getText();
			state = jTextField9.getText();
			DatabaseAdapter adapter = new DatabaseAdapter();
			PreparedStatement statement = adapter
					.insertdata("values(?,?,?,?,?,?,?,?,?)");

			statement.setString(1, fname);
			statement.setString(2, mname);
			statement.setString(3, lname);
			statement.setLong(4, mobileno_long);
			statement.setString(5, houseno);
			statement.setString(6, area);
			statement.setString(7, city);
			statement.setString(8, district);
			statement.setString(9, state);
			int i = 0;
			i = statement.executeUpdate();
			if (i > 0)
				jLabel16.setText("Record is updated successfully..!!");
			adapter.close();

		} catch (Exception e) {
			jLabel16.setText("oops..!!Record is not updated.Fill properly.");
		}

	}

	void setRadiobutton() {
		buttonGroup1.add(jRadioButton1);
		buttonGroup1.add(jRadioButton2);
		buttonGroup1.add(jRadioButton3);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {

				Telephonedirectory telephonedirectory = new Telephonedirectory();
				telephonedirectory.setRadiobutton();
				telephonedirectory.setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JInternalFrame jInternalFrame1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration//GEN-END:variables

}