/*
 * UserInterface.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class UserInterface extends javax.swing.JPanel {

	/** Creates new form UserInterface */
	public UserInterface() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup3 = new javax.swing.ButtonGroup();
		jComboBox1 = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jTextField1 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();

		setBackground(new java.awt.Color(204, 255, 255));

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"First Name", "Middle Name", "Last Name" }));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});
		buttonGroup3.add(jRadioButton1);
		buttonGroup3.add(jRadioButton2);
		buttonGroup3.add(jRadioButton3);
		

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"House no", "Area", "City", "District", "State" }));
		jComboBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox2ActionPerformed(evt);
			}
		});

		jRadioButton1.setText("Telephone No");

		jRadioButton2.setText("Name");
		jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton2ActionPerformed(evt);
			}
		});

		jRadioButton3.setText("Address");

		jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18));
		jLabel1.setText("Search By :");

		jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
		jLabel2.setText("Telephone Directory");

		jButton1.setText("Search");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jTextField1.setText("jTextField1");

		jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14));
		jLabel3.setText("Enter");

		jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14));
		jLabel4.setText("RESULT");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(193, 193,
										193).addComponent(jButton1)
										.addContainerGap(251, Short.MAX_VALUE))
						.addGroup(
								layout.createSequentialGroup().addGap(165, 165,
										165).addComponent(jLabel2)
										.addContainerGap(188, Short.MAX_VALUE))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(29, 29, 29)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addContainerGap())
														.addGroup(
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel3)
																						.addGap(
																								30,
																								30,
																								30)
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addGroup(
																												layout
																														.createSequentialGroup()
																														.addComponent(
																																jRadioButton1)
																														.addContainerGap(
																																324,
																																Short.MAX_VALUE))
																										.addGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												layout
																														.createSequentialGroup()
																														.addGroup(
																																layout
																																		.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.TRAILING)
																																		.addComponent(
																																				jScrollPane1,
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				295,
																																				Short.MAX_VALUE)
																																		.addGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING,
																																				layout
																																						.createSequentialGroup()
																																						.addPreferredGap(
																																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																						.addComponent(
																																								jTextField1,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								295,
																																								Short.MAX_VALUE))
																																		.addGroup(
																																				layout
																																						.createSequentialGroup()
																																						.addGroup(
																																								layout
																																										.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.TRAILING)
																																										.addComponent(
																																												jRadioButton2,
																																												javax.swing.GroupLayout.Alignment.LEADING)
																																										.addComponent(
																																												jRadioButton3,
																																												javax.swing.GroupLayout.Alignment.LEADING))
																																						.addGap(
																																								119,
																																								119,
																																								119)
																																						.addGroup(
																																								layout
																																										.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.TRAILING)
																																										.addComponent(
																																												jComboBox2,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												97,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)
																																										.addComponent(
																																												jComboBox1,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												javax.swing.GroupLayout.DEFAULT_SIZE,
																																												javax.swing.GroupLayout.PREFERRED_SIZE))))
																														.addGap(
																																130,
																																130,
																																130))))
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel1)
																						.addContainerGap(
																								402,
																								Short.MAX_VALUE))))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(19, 19, 19)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												26,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jRadioButton1)
										.addGap(11, 11, 11)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jRadioButton2)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jRadioButton3)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(28, 28, 28)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3))
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				31,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton1)
																		.addGap(
																				27,
																				27,
																				27)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				155,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				58,
																				58,
																				58)
																		.addComponent(
																				jLabel4)
																		.addContainerGap()))));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup3;
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}